### ISSUE TITLE
fb-adb Ignores SIGINT

### ISSUE THREAD

**Issue by niedzielski** [facebook/fb-adb#14]
fb-adb does not respond SIGINT. Previous versions (I'm not sure which) gracefully terminated similar to stock AOSP ADB.

### Repro steps
1. Attach two or more devices.
1. Execute `fb-adb install -r foo.apk`.
1. Observe that the following lines are repeated on the terminal every second:

        error: more than one device/emulator
        - waiting for device -

1. Press control-C.
1. Observe that the process continues running.
1. Press control-Z and SIGKILL the process.

**Comment by dcolascione** [comment]
Thanks for the bug report. Fixed.
