### ISSUE TITLE
fb-adb shell fails when user doesn't own the tty

### ISSUE THREAD

**Issue by BurntBrunch** [facebook/fb-adb#19]
Steps to reproduce:

1. su to another user
2. fb-adb shell cat /proc/meminfo
3. Observe permission denied error for /dev/ttyFOO

This seems to be caused by the hack_reopen_tty usage in cmd_shex.c.

**Comment by dcolascione** [comment]
Try master. Rewrite the TTY management code; now we can use setitimer as a poor man's O_NONBLOCK
