### ISSUE TITLE
fb-adb fails when overwriting device copy

### ISSUE THREAD

**Issue by niedzielski** [facebook/fb-adb#20]
I'm not sure what the scenario that caused it was but it seems I ended up with a copy of fb-adb in /data/local/tmp/fb-adb. `fb-adb shell` printed out the following error:

    fb-adb shell: moving fb-adb to final location failed: mv: overwrite '/data/local/tmp/fb-adb' (Y/n):mv: bad '/data/local/tmp/fb-adb.6CFEB2B64BC7B6EE2F36': No such file or directory

I removed the /data/local/tmp/fb-adb copy using ADB and was able to run fb-adb fine thereafter. I don't know how to repro as it happened only once on an API 23 emulator.

**Comment by dcolascione** [comment]
Thanks. Can repro locally. Seems to be new to API 23.;

**Comment by dcolascione** [comment]
Try it now. See also https://code.google.com/p/android-developer-preview/issues/detail?id=3096&thanks=3096&ts=1440727594

**Comment by niedzielski** [comment]
@dcolascione, works fine on my end. Thanks!

**Comment by niedzielski** [comment]
@dcolascione, sorry I didn't catch this earlier but I think this fix broke behavior on API 19 devices. I'm getting the following error when running `fb-adb -d rcmd screencap -p > screencap.png`:

    fb-adb rcmd: moving fb-adb to final location failed: failed on '-f' - Cross-device link

I hadn't used this device in a while so maybe it's some conflict between fb-adb version differences.

**Comment by dcolascione** [comment]
Huh. I thought KitKat supported -f. Can you try changing "api_level >=
19" to "api_level > 19" in adb.c?

**Comment by niedzielski** [comment]
Thanks, that works. Fixed in https://github.com/facebook/fb-adb/pull/22
