### ISSUE TITLE
"unknown command devices"

### ISSUE THREAD

**Issue by niedzielski** [facebook/fb-adb#25]
Version: ef2c2b1cd222d95e9dbe4296e55b5b8abacc3e90

The follow command fails:
```
$ fb-adb devices                                                                                                                                                         
fb-adb: unknown command devices
```

**Comment by dcolascione** [comment]
fb-adb 2.0 doesn't transparently forward to adb anymore, so this output is now expected. I'd be happy to take a patch that whitelisted commands we *should* forward.

**Comment by rallen** [comment]
> fb-adb 2.0 doesn't transparently forward to adb anymore, so this output is now expected

Could this be reflected in the README?

> fb-adb forwards unknown commands to adb. fb-adb supports the same device-selection options that adb does
https://github.com/facebook/fb-adb#running
