### ISSUE TITLE
fb-adb help may be a binary file

### ISSUE THREAD

**Issue by niedzielski** [facebook/fb-adb#26]
Version: ef2c2b1cd222d95e9dbe4296e55b5b8abacc3e90

The following command makes an ominous query:

```
$ fb-adb help
"/tmp/fb-adb-qRIICl" may be a binary file.  See it anyway?
```

**Comment by dcolascione** [comment]
On what system? Mind attaching the contents of that file?

**Comment by niedzielski** [comment]
Hrm, well this is embarrassing but I can't reproduce the issue at all now. I'll collect more details if it happens again.
