### ISSUE TITLE
build instructions don't work on Mac

### ISSUE THREAD

**Issue by tcmulcahy** [facebook/fb-adb#28]
This is what I get. It works fine on Ubuntu though.

Making all in stub-x86
Making all in stub-arm
Making all in stub-x86-pic
Making all in stub-arm-pic
/Library/Developer/CommandLineTools/usr/bin/make -C stub-x86/ FB_ADB_RECURSIVE=1 libfb-adb.a.stripped
i686-linux-android-gcc -DPACKAGE_NAME=\"fb-adb\" -DPACKAGE_TARNAME=\"fb-adb\" -DPACKAGE_VERSION=\"1.99.99-4\" -DPACKAGE_STRING=\"fb-adb\ 1.99.99-4\" -DPACKAGE_BUGREPORT=\"dancol@fb.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"fb-adb\" -DVERSION=\"1.99.99-4\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DSIZEOF_OFF_T=4 -DHAVE_MACHINE_ENDIAN_H=1 -DHAVE_ENDIAN_H=1 -DHAVE_FEATURES_H=1 -DHAVE_PIPE2=1 -DHAVE_PTSNAME=1 -DHAVE_FUNOPEN=1 -DHAVE_CLOCK_GETTIME=1 -DHAVE_FTRUNCATE64=1 -DHAVE_REALPATH=1 -DHAVE_STRUCT_STAT_ST_BLOCKS=1 -DHAVE_STRUCT_STAT_ST_BLKSIZE=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DHAVE_STRUCT_DIRENT_D_TYPE=1 -I. -I../../stub-x86/..  -I. -DSHA2_USE_INTTYPES_H=1 -DFBADB_STUB=1  -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -DNDEBUG=1 -fvisibility=hidden -std=gnu99 -Wno-free-nonheap-object -Wno-initializer-overrides   -g -O2 -MT adb.o -MD -MP -MF .deps/adb.Tpo -c -o adb.o ../../stub-x86/../adb.c
i686-linux-android-gcc: error trying to exec 'cc1': execvp: No such file or directory
make[2]: *** [adb.o] Error 1
make[1]: *** [stub-x86/.update-lib] Error 2
make: *** [all-recursive] Error 1

**Comment by dcolascione** [comment]
I believe this issue a make incompatibility; try installing the latest GNU Make with brew for now.

**Comment by tcmulcahy** [comment]
This worked. I believe the following magic is needed on Mac:
brew install autoconf
brew install automake
brew install coreutils
brew install gcc
brew tap homebrew/dupes
brew install homebrew/dupes/make

This last step installs make 4.1 under the alias gmake, with which I can successfully build fb-adb.
