### ISSUE TITLE
Can I build in windows?many errors！

### ISSUE THREAD

**Issue by wanderdeng** [facebook/fb-adb#33]
In ununtu,I have finished compiling。
But in windows,build with many errors。
Some one build sucess with windows？（fb-adb.exe）

I usb cygwin and android-ndk，build with error：

../fdrecorder.c: In function 'fdrecorder_new':
../fdrecorder.c:127:53: error: 'O_ASYNC' undeclared (first use in this function)
     xF_SETFL(fdr->pipe[0], xF_GETFL(fdr->pipe[0]) | O_ASYNC | O_NONBLOCK);
                                                     ^
../fdrecorder.c:127:53: note: each undeclared identifier is reported only once for each function it appears in
../fdrecorder.c: At top level:
cc1: warning: unrecognized command line option "-Wno-initializer-overrides"
Makefile:690: recipe for target 'fdrecorder.o' failed
make[1]: *** [fdrecorder.o] Error 1
make[1]: Leaving directory '/home/GAOXIAN/fb-adb-master/build'
Makefile:753: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Someone know how to confirm？？

**Comment by dcolascione** [comment]
Windows is not a supported platform at this time. Porting to Cygwin shouldn't be _that_ hard if so you feel so inclined. Cygwin doesn't support O_ASYNC the last time I checked, so you'd probably have to make fdrecorder use a temporary file instead.

**Comment by wanderdeng** [comment]
think you！can I make with mingw?
