### ISSUE TITLE
EV_RECEIPT maybe missing on other BSDs

### ISSUE THREAD

**Issue by jbeich** [facebook/fb-adb#38]
fb-adb [fails](http://muscles.dragonflybsd.org/bulk/latest-per-pkg/fb-adb/1.4.4.113/bleeding-edge-potential.log) to build on DragonFly (and NetBSD) with
```c++
fs.c: In function 'xppoll':
fs.c:540:35: error: 'EV_RECEIPT' undeclared (first use in this function)
             kev->flags = EV_ADD | EV_RECEIPT;
                                   ^
fs.c:540:35: note: each undeclared identifier is reported only once for each function it appears in
```
After poking source:
- `EV_RECEIPT` is available on FreeBSD (since 8.1) and OS X (since 10.5)
- `ppoll()` is available on Linux, Solaris (circa 2010), OpenBSD (since 5.4) and FreeBSD (since 10.2)

@jrmarino, @tnn2, do you think DragonFly or NetBSD folks are interested in implementing either of those?

**Comment by jrmarino** [comment]
On 12/2/2015 8:22 PM, Jan Beich wrote:
> @jrmarino <https://github.com/jrmarino>, @tnn2
> <https://github.com/tnn2>, do you think DragonFly or NetBSD folks are
> interested in implementing either of those?

Yeah, I'll put it on my todo list and see if we can get those implemented.

Thanks,
John

**Comment by dcolascione** [comment]
I'd also love to see properly-supported ppoll and pselect implementations. It's much less awkward to implement those in the kernel than to emulate them using kqueue.

**Comment by jrmarino** [comment]
it appears EV_RECEIPT is trivial so this one should be crossed off shortly, at least in master.  I'll think about if it should be backported to release 4.4 branch.

I haven't looked at ppoll at all though.

**Comment by jrmarino** [comment]
one down: https://github.com/DragonFlyBSD/DragonFlyBSD/commit/790e2e546ea2fa0a2da2055c14d439ba2cb5edfb

**Comment by jrmarino** [comment]
That was enough to fix fb-adb; it's been imported into dports:
https://github.com/DragonFlyBSD/DPorts/commit/1a0ffdfff8f7d8d8590f483779a58e5a29941c8b

Apparently ppoll has an alternative if it's not present.  (we're still working on adding it though)

**Comment by jbeich** [comment]
Thanks. `EV_RECEIPT` is also used by devel/libdispatch which you may to check if it builds now.

As for ppoll(2) the list of consumers in ports is larger. A quick grep(1) shows:
- audio/jack (timeout)
- audio/pulseaudio (timeout)
- comms/usbmuxd (sigmask)
- devel/fb-adb (sigmask)
- devel/skalibs (timeout)
- emulators/qemu* (timeout)
- graphics/gnash (sigmask)
- lang/erlang-runtime18 (timeout)
- lang/gambit-c (timeout)
- lang/mit-scheme (sigmask)
- lang/ruby* (timeout)
- multimedia/gstreamer{,1} (timeout)
- net/asterisk* (timeout)
- net/ndisc6 (sigmask)
- sysutils/mcelog (sigmask, disabled)
- sysutils/pesign (unnecessary)

**Comment by jrmarino** [comment]
no joy on libdispatch; there are other issues: http://muscles.dragonflybsd.org/bulk/bleeding-edge-potential/20151205_071609/logs/errors/libdispatch-210_1.log

thanks fo the ppoll impacts.  It appears that it's still optional for the most part since most of those are building.  In any case, I think we'll get it sooner rather than later. Thanks!

**Comment by tnn2** [comment]
Hi, for now I've logged PR [50506](http://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=50506) in the NetBSD bug tracker, citing this issue.

**Comment by jbeich** [comment]
... and landed in https://github.com/IIJ-NetBSD/netbsd-src/commit/fe672be45b288bad28419f6b8f96214435f2ad5f (git mirror). fb-adb now builds fine on NetBSD, including Android stubs using 0313e4c trick.

Closing per fixes by OS vendors.
