### ISSUE TITLE
`make all` does not work out of the box on OSX

### ISSUE THREAD

**Issue by mzlee** [facebook/fb-adb#44]
The stub toolchains are not automatically picked up while building on OSX which causes the compilation to basically fail immediately. Adding 'toolchain/bin' to my PATH and running the individual build commands does work.

**Comment by dcolascione** [comment]
config.log output?

**Comment by markshep** [comment]
I'm seeing the same.  Please see attached [config.log.txt](https://github.com/facebook/fb-adb/files/495238/config.log.txt).

**Comment by markshep** [comment]
Ah, running `gmake` instead of `make` got gcc working.  I'm getting Java errors now, but I guess that's a separate issue.

**Comment by markshep** [comment]
I've done a bit more digging and the standard version of make on OSX is actually GNU make rather than BSD make, which I had initially assumed.  However it's version 3.81, which is presumably too old.  Using GNU make 4.1 works (I use the [MacPorts](https://www.macports.org/) one).

**Comment by mzlee** [comment]
Yep, gmake versus make. Maybe we can display it more prominently.
