### ISSUE TITLE
Installing apk does not work

### ISSUE THREAD

**Issue by aherbjornsen** [facebook/fb-adb#61]
I've successfully built fb-adb on my Ubuntu 17.04.

As far as I can see most commands work fine (I've tried 'shell', 'logcat-json', 'ping' and a few others).

But when I try to install an apk with the command:

`fb-adb install <apk-name>`

I just get the error message:

`fb-adb: unknown command install`

Needless to say, `adb install <apk-name>` works just fine.

**Comment by BurntBrunch** [comment]
fb-adb is not a drop-in replacement for adb. In particular commands like `install` are out of scope for support.

One *could* emulate `adb install` as `fb-adb fput app.apk /data/local/tmp/app.apk && fb-adb rcmd pm install /data/local/tmp/app.apk` but it's obviously easier to just do `adb install` in the first place.
